fullnameOverride: ""

config:
  ROOT_URL: "http://titra.com"
  PORT: "3000"
  MONGO_INITDB_DATABASE: "titra"

titra:
  replicas: 1
  image:
    repository: mxk77/titra_app
    tag: latest
    pullPolicy: Always
  containerPort: 3000
  readinessProbe:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 5
  livenessProbe:
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10
  service:
    port: 3000
    type: LoadBalancer
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

mongodb:
  replicas: 1
  image: "mongo:4.4"
  storage: "5Gi" # The storage size to request
  storageClassName: "ebs-sc" # The StorageClass you defined for EBS
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30

ingress:
  enabled: false
  class: "nginx"
  backendProtocol: "HTTP"
  host: "titra.com"
