---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "titra-chart.fullname" . }}-mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      name: mongodb
  clusterIP: None
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "titra-chart.fullname" . }}-mongodb
  labels:
    app: mongodb
spec:
  serviceName: "{{ include "titra-chart.fullname" . }}-mongodb"
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image | quote }}
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.config.MONGO_INITDB_DATABASE | quote }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: {{ .Values.mongodb.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mongodb.readinessProbe.periodSeconds }}
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: {{ .Values.mongodb.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mongodb.livenessProbe.periodSeconds }}
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.mongodb.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.mongodb.storage | quote }}